### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by joe9** [pikatchu/LinearML#17]
Hello,

Thanks for sharing LinearML.

This seems to be a good idea. Just want to check if you found any other language that can do what LinearML set out for?

Thanks

**Comment by hawkw** [comment]
I'm not @pikatchu, but I bet you'd probably like Rust.

**Comment by boomshroom** [comment]
@hawkw I'm not @joe9, but I do like Rust. I just don't like how it has a monopoly on static memory safety.

**Comment by hawkw** [comment]
@boomshroom totally agree, would love to see static memory safety become widespread; my response was directed specifically at @joe9's question regarding other languages with similar goals.

**Comment by olleharstedt** [comment]
It's worth pointing out that Rust does not support linear types (yet), and that linear types have a broader use-case than safe memory management.
