### ISSUE TITLE
exception Assert_failure("emit.ml", 213, 34)

### ISSUE THREAD

**Issue by magnusjonsson** [pikatchu/LinearML#5]
Minimal program to reproduce:

```
module Main = struct
  val main: unit -> unit 
  let main() =
    let d = ()
    in (fun () -> d) ()
end
```

(It doesn't seem to matter whether fun or !fun is used.)

**Comment by pikatchu** [comment]
Many thanks!

I just fixed it. I added your example in regression. Strangely I get a warning from llvm now ... this is odd.

**Comment by magnusjonsson** [comment]
Nice! Maybe issue #6 can shed some light on the llvm warning.

**Comment by pikatchu** [comment]
Ah closure are really sketchy in the back-end right now ... 
You will find many of those :-)
However it's good because it helps me building a regression test base!
I will look into that as soon as I can.

Thanks!
